fix: correct global variable annotation for Python versions prior to 3.8
This fixes the following syntax error reported by python 3.7

File "/usr/local/lib/python3.7/site-packages/esp_idf_sbom/libsbom/expr.py", line 96
    _variables: Dict[str, Any] = {}
    ^
SyntaxError: annotated name '_variables' can't be global

This is caused by a bug in CPython (https://bugs.python.org/issue34939)
where the annotation of global variables is reported as an error if used
with forward references.

Signed-off-by: Frantisek Hrbata <frantisek.hrbata@espressif.com>